//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtodelDBFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int TicketID { get; set; }
        public int SeatNo { get; set; }
        public System.DateTime TicketDate { get; set; }
        public string Customer_CustomerID { get; set; }
        public string Expedition_ExpeditionID { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Expedition Expedition { get; set; }
    }
}
